### ISSUE TITLE
Blog list view at mobile device is messy

### ISSUE THREAD

**Issue by daijiang** [rbind/daijiang#1]
changing `@media` part in `static/CSS/custom.css` does not work...

Any ideas how to fix this?

**Comment by daijiang** [comment]
solved with:

```css
@media screen and (max-width: 480px) {
  .archive {
    line-height: 0.8em;
    text-align: left;
  }
  
  .archive-title {
    font-size: 19px;
  }

  .archive-item-date {
    text-align: left;
    float: left;
    font-size: 13px;
    max-width: 15%;
  }

  .archive-item-link {
    text-overflow: ellipsis;
    max-width: 80%;
    white-space: nowrap;
    overflow: hidden;
    font-size: 15px;
  }
}
```
